package p24;

import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author 18PROGB0073
 */
public class frmInicio extends javax.swing.JFrame {

    /**
     * Creates new form frmInicio
     */
    public frmInicio() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        lblConvertir = new javax.swing.JLabel();
        lblMetros = new javax.swing.JLabel();
        lblResulM = new javax.swing.JLabel();
        txtMetros = new javax.swing.JTextField();
        txtResulM = new javax.swing.JTextField();
        lblHoras = new javax.swing.JLabel();
        lblResulH = new javax.swing.JLabel();
        txtHoras = new javax.swing.JTextField();
        txtResulH = new javax.swing.JTextField();
        lblKG = new javax.swing.JLabel();
        lblGramos = new javax.swing.JLabel();
        btnConvierte = new javax.swing.JButton();
        lblKiGra = new javax.swing.JLabel();
        jrbCentimetros = new javax.swing.JRadioButton();
        jrbMilimetros = new javax.swing.JRadioButton();
        jrbMinutos = new javax.swing.JRadioButton();
        jrbSegundos = new javax.swing.JRadioButton();
        txtKG = new javax.swing.JTextField();
        txtGramos = new javax.swing.JTextField();
        jrbDer = new javax.swing.JRadioButton();
        jrbIzq = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        lblTitulo.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        lblTitulo.setText("Conversiones-P24");

        lblConvertir.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblConvertir.setText("A convertir");

        lblMetros.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblMetros.setText("Metros");

        lblResulM.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblResulM.setText("Resultado");

        txtMetros.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        txtResulM.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtResulM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtResulMActionPerformed(evt);
            }
        });

        lblHoras.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblHoras.setText("Horas");

        lblResulH.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblResulH.setText("Resultado");

        txtHoras.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        txtResulH.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtResulH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtResulHActionPerformed(evt);
            }
        });

        lblKG.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblKG.setText("KG");

        lblGramos.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblGramos.setText("Gramos");

        btnConvierte.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnConvierte.setText("Convierte");
        btnConvierte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConvierteActionPerformed(evt);
            }
        });

        lblKiGra.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblKiGra.setText("Kilos<->Gramos");

        jrbCentimetros.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jrbCentimetros.setText("Centimetros");
        jrbCentimetros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbCentimetrosActionPerformed(evt);
            }
        });

        jrbMilimetros.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jrbMilimetros.setText("Milimetros");
        jrbMilimetros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbMilimetrosActionPerformed(evt);
            }
        });

        jrbMinutos.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jrbMinutos.setText("Minutos");
        jrbMinutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbMinutosActionPerformed(evt);
            }
        });

        jrbSegundos.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jrbSegundos.setText("Segundos");
        jrbSegundos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbSegundosActionPerformed(evt);
            }
        });

        txtKG.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtKG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKGActionPerformed(evt);
            }
        });

        txtGramos.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtGramos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGramosActionPerformed(evt);
            }
        });

        jrbDer.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jrbDer.setText("------>");
        jrbDer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbDerActionPerformed(evt);
            }
        });

        jrbIzq.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jrbIzq.setText("<------");
        jrbIzq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbIzqActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtKG, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblKiGra)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(20, 20, 20)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jrbDer)
                                            .addComponent(jrbIzq))
                                        .addGap(59, 59, 59)
                                        .addComponent(txtGramos, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(lblTitulo))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(txtResulM, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblHoras)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(6, 6, 6)
                                                .addComponent(lblConvertir))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(txtMetros, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(txtHoras, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(60, 60, 60)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jrbCentimetros)
                                                    .addComponent(jrbMinutos)
                                                    .addComponent(jrbMilimetros)
                                                    .addComponent(jrbSegundos))))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(txtResulH, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                        .addComponent(lblResulH)
                                                        .addGap(24, 24, 24))))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(95, 95, 95)
                                                .addComponent(lblResulM)
                                                .addGap(0, 24, Short.MAX_VALUE)))))
                                .addGap(59, 59, 59))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblMetros)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(20, 20, 20)
                                        .addComponent(lblKG)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblGramos)
                                        .addGap(76, 76, 76)))
                                .addComponent(btnConvierte)))
                        .addGap(47, 47, 47))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(lblTitulo)
                .addGap(18, 18, 18)
                .addComponent(lblConvertir)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(lblMetros))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jrbCentimetros)
                                    .addComponent(lblResulM))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtMetros, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jrbMilimetros)
                            .addComponent(txtResulM, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(jrbMinutos)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jrbSegundos))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblHoras)
                                    .addComponent(lblResulH))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtResulH)
                                    .addComponent(txtHoras))))
                        .addGap(50, 50, 50)
                        .addComponent(lblKiGra)
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnConvierte)
                            .addComponent(lblKG)
                            .addComponent(lblGramos))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jrbDer, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jrbIzq)
                                .addGap(15, 15, 15))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(txtKG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32)))
                        .addGap(34, 34, 34))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtGramos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(64, 64, 64))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtResulMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtResulMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtResulMActionPerformed

    private void jrbCentimetrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbCentimetrosActionPerformed
        try {
            jrbCentimetros.setSelected(true);
            jrbMilimetros.setSelected(false);
            double Centimetros = Double.parseDouble(txtMetros.getText());
            txtResulM.setText(String.valueOf(Centimetros * 100));
            txtMetros.setText("");
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(null, "Error,debes ingresar un numero");
        }
    }//GEN-LAST:event_jrbCentimetrosActionPerformed

    private void jrbMilimetrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbMilimetrosActionPerformed
        try {
            jrbMilimetros.setSelected(true);
            jrbCentimetros.setSelected(false);
            double Milimetros = Double.parseDouble(txtMetros.getText());
            txtResulM.setText(String.valueOf(Milimetros * 1000));
            txtMetros.setText("");
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(null, "Error,debes ingresar un numero");
        }
    }//GEN-LAST:event_jrbMilimetrosActionPerformed

    private void jrbMinutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbMinutosActionPerformed
        try {
            jrbMinutos.setSelected(true);
            jrbSegundos.setSelected(false);
            double Minutos = Double.parseDouble(txtHoras.getText());
            txtResulH.setText(String.valueOf(Minutos * 60));
            txtHoras.setText("");
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(null, "Error,debes ingresar un numero");
        }
    }//GEN-LAST:event_jrbMinutosActionPerformed

    private void jrbSegundosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbSegundosActionPerformed
        try {
            jrbSegundos.setSelected(true);
            jrbMinutos.setSelected(false);
            double Segundos = Double.parseDouble(txtHoras.getText());
            txtResulH.setText(String.valueOf(Segundos * 3600));
            txtHoras.setText("");
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(null, "Error,debes ingresar un numero");
        }
    }//GEN-LAST:event_jrbSegundosActionPerformed

    private void jrbDerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbDerActionPerformed
        try {
            jrbDer.setSelected(true);
            jrbIzq.setSelected(false);
            txtGramos.setEnabled(true);
            txtKG.setEnabled(false);
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(null, "Error,debes ingresar un numero");
        }
    }//GEN-LAST:event_jrbDerActionPerformed

    private void jrbIzqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbIzqActionPerformed
        try {
            jrbIzq.setSelected(true);
            jrbDer.setSelected(false);
            txtKG.setEnabled(true);
            txtGramos.setEnabled(false);
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(null, "Error,debes ingresar un numero");
        }
    }//GEN-LAST:event_jrbIzqActionPerformed

    private void txtKGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKGActionPerformed

    }//GEN-LAST:event_txtKGActionPerformed

    private void txtGramosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGramosActionPerformed

    }//GEN-LAST:event_txtGramosActionPerformed

    private void txtResulHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtResulHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtResulHActionPerformed

    private void btnConvierteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConvierteActionPerformed
        if (jrbDer.isSelected()) {
            double Gramos = Double.parseDouble(txtGramos.getText());
            txtGramos.setText(String.valueOf(Gramos / 1000));
            txtGramos.setText("");
        } else {
            double Kilos = Double.parseDouble(txtKG.getText());
            txtKG.setText(String.valueOf(Kilos * 1000));
            txtKG.setText("");
        }

    }//GEN-LAST:event_btnConvierteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmInicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConvierte;
    private javax.swing.JRadioButton jrbCentimetros;
    private javax.swing.JRadioButton jrbDer;
    private javax.swing.JRadioButton jrbIzq;
    private javax.swing.JRadioButton jrbMilimetros;
    private javax.swing.JRadioButton jrbMinutos;
    private javax.swing.JRadioButton jrbSegundos;
    private javax.swing.JLabel lblConvertir;
    private javax.swing.JLabel lblGramos;
    private javax.swing.JLabel lblHoras;
    private javax.swing.JLabel lblKG;
    private javax.swing.JLabel lblKiGra;
    private javax.swing.JLabel lblMetros;
    private javax.swing.JLabel lblResulH;
    private javax.swing.JLabel lblResulM;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTextField txtGramos;
    private javax.swing.JTextField txtHoras;
    private javax.swing.JTextField txtKG;
    private javax.swing.JTextField txtMetros;
    private javax.swing.JTextField txtResulH;
    private javax.swing.JTextField txtResulM;
    // End of variables declaration//GEN-END:variables
}
